/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTreatmentQueueIndexRouteImport } from './routes/dashboard/treatment-queue/index'
import { Route as DashboardTransactionsIndexRouteImport } from './routes/dashboard/transactions/index'
import { Route as DashboardShimentsIndexRouteImport } from './routes/dashboard/shiments/index'
import { Route as DashboardRulesIndexRouteImport } from './routes/dashboard/rules/index'
import { Route as DashboardOperationsIndexRouteImport } from './routes/dashboard/operations/index'
import { Route as DashboardDailyNewsIndexRouteImport } from './routes/dashboard/daily-news/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTreatmentQueueIndexRoute =
  DashboardTreatmentQueueIndexRouteImport.update({
    id: '/treatment-queue/',
    path: '/treatment-queue/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTransactionsIndexRoute =
  DashboardTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardShimentsIndexRoute = DashboardShimentsIndexRouteImport.update({
  id: '/shiments/',
  path: '/shiments/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRulesIndexRoute = DashboardRulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOperationsIndexRoute =
  DashboardOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDailyNewsIndexRoute = DashboardDailyNewsIndexRouteImport.update({
  id: '/daily-news/',
  path: '/daily-news/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard/daily-news/': typeof DashboardDailyNewsIndexRoute
  '/dashboard/operations/': typeof DashboardOperationsIndexRoute
  '/dashboard/rules/': typeof DashboardRulesIndexRoute
  '/dashboard/shiments/': typeof DashboardShimentsIndexRoute
  '/dashboard/transactions/': typeof DashboardTransactionsIndexRoute
  '/dashboard/treatment-queue/': typeof DashboardTreatmentQueueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/dashboard/daily-news': typeof DashboardDailyNewsIndexRoute
  '/dashboard/operations': typeof DashboardOperationsIndexRoute
  '/dashboard/rules': typeof DashboardRulesIndexRoute
  '/dashboard/shiments': typeof DashboardShimentsIndexRoute
  '/dashboard/transactions': typeof DashboardTransactionsIndexRoute
  '/dashboard/treatment-queue': typeof DashboardTreatmentQueueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard/daily-news/': typeof DashboardDailyNewsIndexRoute
  '/dashboard/operations/': typeof DashboardOperationsIndexRoute
  '/dashboard/rules/': typeof DashboardRulesIndexRoute
  '/dashboard/shiments/': typeof DashboardShimentsIndexRoute
  '/dashboard/transactions/': typeof DashboardTransactionsIndexRoute
  '/dashboard/treatment-queue/': typeof DashboardTreatmentQueueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/login/'
    | '/dashboard/daily-news/'
    | '/dashboard/operations/'
    | '/dashboard/rules/'
    | '/dashboard/shiments/'
    | '/dashboard/transactions/'
    | '/dashboard/treatment-queue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/daily-news'
    | '/dashboard/operations'
    | '/dashboard/rules'
    | '/dashboard/shiments'
    | '/dashboard/transactions'
    | '/dashboard/treatment-queue'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/login/'
    | '/dashboard/daily-news/'
    | '/dashboard/operations/'
    | '/dashboard/rules/'
    | '/dashboard/shiments/'
    | '/dashboard/transactions/'
    | '/dashboard/treatment-queue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/treatment-queue/': {
      id: '/dashboard/treatment-queue/'
      path: '/treatment-queue'
      fullPath: '/dashboard/treatment-queue/'
      preLoaderRoute: typeof DashboardTreatmentQueueIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transactions/': {
      id: '/dashboard/transactions/'
      path: '/transactions'
      fullPath: '/dashboard/transactions/'
      preLoaderRoute: typeof DashboardTransactionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/shiments/': {
      id: '/dashboard/shiments/'
      path: '/shiments'
      fullPath: '/dashboard/shiments/'
      preLoaderRoute: typeof DashboardShimentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/rules/': {
      id: '/dashboard/rules/'
      path: '/rules'
      fullPath: '/dashboard/rules/'
      preLoaderRoute: typeof DashboardRulesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/operations/': {
      id: '/dashboard/operations/'
      path: '/operations'
      fullPath: '/dashboard/operations/'
      preLoaderRoute: typeof DashboardOperationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/daily-news/': {
      id: '/dashboard/daily-news/'
      path: '/daily-news'
      fullPath: '/dashboard/daily-news/'
      preLoaderRoute: typeof DashboardDailyNewsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDailyNewsIndexRoute: typeof DashboardDailyNewsIndexRoute
  DashboardOperationsIndexRoute: typeof DashboardOperationsIndexRoute
  DashboardRulesIndexRoute: typeof DashboardRulesIndexRoute
  DashboardShimentsIndexRoute: typeof DashboardShimentsIndexRoute
  DashboardTransactionsIndexRoute: typeof DashboardTransactionsIndexRoute
  DashboardTreatmentQueueIndexRoute: typeof DashboardTreatmentQueueIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDailyNewsIndexRoute: DashboardDailyNewsIndexRoute,
  DashboardOperationsIndexRoute: DashboardOperationsIndexRoute,
  DashboardRulesIndexRoute: DashboardRulesIndexRoute,
  DashboardShimentsIndexRoute: DashboardShimentsIndexRoute,
  DashboardTransactionsIndexRoute: DashboardTransactionsIndexRoute,
  DashboardTreatmentQueueIndexRoute: DashboardTreatmentQueueIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
